"""initial schema

Revision ID: 6fa58041c7e7
Revises:
Create Date: 2026-01-22 14:03:03.633420

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "6fa58041c7e7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def create_enum_if_not_exists(conn, enum_name, values):
    """Create PostgreSQL ENUM type only if it doesn't exist"""
    result = conn.execute(
        sa.text(f"SELECT 1 FROM pg_type WHERE typname = '{enum_name}'")
    ).fetchone()

    if not result:
        enum_type = postgresql.ENUM(*values, name=enum_name)
        enum_type.create(conn)
        return True
    return False


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()

    # Create all ENUM types FIRST
    create_enum_if_not_exists(
        conn,
        "musclegroup",
        ["CHEST", "BACK", "SHOULDERS", "ARMS", "LEGS", "CORE", "CALVES", "FULL_BODY"],
    )
    create_enum_if_not_exists(
        conn,
        "equipment",
        [
            "BARBELL",
            "DUMBBELLS",
            "CABLE_MACHINE",
            "MACHINE",
            "BODYWEIGHT",
            "KETTLEBELL",
            "MEDICINE_BALL",
            "RESISTANCE_BAND",
            "CARDIO",
        ],
    )
    create_enum_if_not_exists(conn, "userrole", ["COACH", "ADMIN", "USER"])
    create_enum_if_not_exists(
        conn, "settype", ["WARMUP", "NORMAL", "FAILURE", "DROPSET"]
    )
    create_enum_if_not_exists(
        conn, "sessionstatus", ["IN_PROGRESS", "COMPLETED", "CANCELLED"]
    )
    create_enum_if_not_exists(
        conn, "sessionsetstatus", ["PENDING", "COMPLETED", "SKIPPED"]
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercise",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column(
            "muscle_group",
            postgresql.ENUM(
                "CHEST",
                "BACK",
                "SHOULDERS",
                "ARMS",
                "LEGS",
                "CORE",
                "CALVES",
                "FULL_BODY",
                name="musclegroup",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "equipment",
            postgresql.ENUM(
                "BARBELL",
                "DUMBBELLS",
                "CABLE_MACHINE",
                "MACHINE",
                "BODYWEIGHT",
                "KETTLEBELL",
                "MEDICINE_BALL",
                "RESISTANCE_BAND",
                "CARDIO",
                name="equipment",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(
                "COACH", "ADMIN", "USER", name="userrole", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "workout",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workout_exercise",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercise.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workout.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workout_session",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="sessionstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workout.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "session_exercise",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("workout_exercise_id", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["workout_session.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workout_exercise_id"],
            ["workout_exercise.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workout_set",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("reps", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column(
            "set_type",
            postgresql.ENUM(
                "WARMUP",
                "NORMAL",
                "FAILURE",
                "DROPSET",
                name="settype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("workout_exercise_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workout_exercise_id"],
            ["workout_exercise.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "session_set",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_exercise_id", sa.Integer(), nullable=False),
        sa.Column("workout_set_id", sa.Integer(), nullable=True),
        sa.Column("planned_reps", sa.Integer(), nullable=False),
        sa.Column("planned_weight", sa.Integer(), nullable=False),
        sa.Column("actual_reps", sa.Integer(), nullable=True),
        sa.Column("actual_weight", sa.Integer(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "COMPLETED",
                "SKIPPED",
                name="sessionsetstatus",
                create_type=False,
            ),
            nullable=False,
        ),  # FIXED TYPO!
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_exercise_id"],
            ["session_exercise.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workout_set_id"],
            ["workout_set.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session_set")
    op.drop_table("workout_set")
    op.drop_table("session_exercise")
    op.drop_table("workout_session")
    op.drop_table("workout_exercise")
    op.drop_table("workout")
    op.drop_table("users")
    op.drop_table("exercise")

    # Drop all ENUMs
    conn = op.get_bind()
    conn.execute(sa.text("DROP TYPE IF EXISTS sessionsetstatus CASCADE"))
    conn.execute(sa.text("DROP TYPE IF EXISTS sessionstatus CASCADE"))
    conn.execute(sa.text("DROP TYPE IF EXISTS settype CASCADE"))
    conn.execute(sa.text("DROP TYPE IF EXISTS userrole CASCADE"))
    conn.execute(sa.text("DROP TYPE IF EXISTS equipment CASCADE"))
    conn.execute(sa.text("DROP TYPE IF EXISTS musclegroup CASCADE"))
    # ### end Alembic commands ###
